Repository TVT19KMO/tvt19kmo-app, pull requests merged in 2021-04, with the labels that each got.

#15 Create BaseInput component and add styling.
  src/App.vue
  src/components/BaseInput.vue
  src/main.js
Labels: UI/UX, application

#16 Create BaseButton component and add styling.
  src/App.vue
  src/components/BaseButton.vue
  src/main.js
Labels: UI/UX, application

#17 Create some very basic and reusable components.
  README.md
  deploy.sh
  gh-pages-deploy.js
  package-lock.json
  package.json
  src/App.vue
  src/components/ActivityChart.vue
  src/components/BaseButton.vue
  src/components/BaseForm.vue
  src/components/BaseInput.vue
  src/components/BaseList.vue
  src/components/BaseTable.vue
  src/components/Heading.vue
  src/components/TheFooter.vue
  src/components/TheHeader.vue
  src/components/tasks/TaskForm.vue
  src/components/tasks/TaskList.vue
  src/components/tasks/TaskListRow.vue
  src/main.js
  src/styles/theme.js
  tailwind.config.js
  vite.config.js
Labels: UI/UX, application

#23 Unit test setup.
  .eslintrc.js
  README.md
  jest.config.js
  package-lock.json
  package.json
  tests/.eslintrc.js
  tests/unit/components/BaseButton.spec.js
Labels: application, unit tests

#25 Unit test setup.
  .eslintrc.js
  README.md
  jest.config.js
  package-lock.json
  package.json
  tests/.eslintrc.js
  tests/unit/components/BaseButton.spec.js
Labels: application, unit tests

#30 Feature/api fetch tasks
  .eslintrc.js
  README.md
  index.html
  jest.config.js
  package-lock.json
  package.json
  src/api/index.js
  src/api/setup.js
  src/api/tasks.js
  src/components/tasks/TaskList.vue
  tests/.eslintrc.js
  tests/unit/components/BaseButton.spec.js
Labels: application

#32 Fix create module for API requests.
  src/api/index.js
  src/api/setup.js
  src/api/tasks.js
  src/components/tasks/TaskList.vue
Labels: application

#33 Setup Vuex state management and update TaskList to use it.
  package-lock.json
  package.json
  src/components/tasks/TaskList.vue
  src/main.js
  src/store/index.js
  src/store/tasks/actions.js
  src/store/tasks/index.js
  src/store/tasks/mutations.js
  src/store/tasks/state.js
Labels: application, enhancement

#35 Stripe integration
  package-lock.json
  package.json
  src/api/index.js
  src/api/payments.js
  src/api/products.js
  src/api/setup.js
  src/assets/coin_10000.png
  src/assets/coin_20000.png
  src/assets/coin_5000.png
  src/components/BaseList.vue
  src/components/BaseModal.vue
  src/components/Heading.vue
  src/components/PurchaseModal.vue
  src/components/StripePurchase.vue
  src/components/TheHeader.vue
  src/compositions/index.js
  src/compositions/useProducts.js
  src/main.js
  src/store/index.js
  src/store/products/actions.js
  src/store/products/index.js
  src/store/products/mutations.js
  src/store/products/state.js
  src/styles/theme.js
  src/views/MainPage.vue
Labels: UI/UX, application, feature

#38 Add basic CRUD logic for tasks.
  package-lock.json
  package.json
  src/api/tasks.js
  src/components/tasks/TaskEditModal.vue
  src/components/tasks/TaskForm.vue
  src/components/tasks/TaskList.vue
  src/main.js
  src/store/tasks/actions.js
  src/store/tasks/getters.js
  src/store/tasks/index.js
  src/store/tasks/mutations.js
  src/store/tasks/state.js
  src/store/tasks/utils.js
  src/views/TasksPage.vue
Labels: UI/UX, application, feature

#40 User authentication (register, login, logout)
  package-lock.json
  package.json
  src/App.vue
  src/api/index.js
  src/api/setup.js
  src/api/users.js
  src/assets/bg_1.jpeg
  src/components/BaseButton.vue
  src/components/BaseInput.vue
  src/components/StripeCheckoutButton.vue
  src/components/TheFooter.vue
  src/components/TheHeader.vue
  src/components/tasks/TaskList.vue
  src/main.js
  src/routes.js
  src/store/index.js
  src/store/user/actions.js
  src/store/user/getters.js
  src/store/user/index.js
  src/store/user/mutations.js
  src/store/user/state.js
  src/views/LoginPage.vue
  src/views/RegistrationPage.vue
  src/views/TasksPage.vue
  src/views/index.js
Labels: UI/UX, application, enhancement

#45 User can select children for tasks.
  src/api/children.js
  src/components/tasks/TaskAssignModal.vue
  src/routes.js
Labels: application, feature

#48 Mark tasks as completed. Assign tasks to children.
  package-lock.json
  package.json
  src/api/tasks.js
  src/components/TheHeader.vue
  src/components/tasks/AssignmentTaskList.vue
  src/components/tasks/TaskAssignModal.vue
  src/compositions/useTasks.js
  src/main.js
  src/store/children/actions.js
  src/store/index.js
  src/store/tasks/actions.js
  src/store/tasks/getters.js
  src/store/tasks/index.js
  src/store/tasks/mutations.js
  src/store/tasks/state.js
  src/store/user/mutations.js
  src/views/AuthPage.vue
  src/views/MainPage.vue
  src/views/TasksPage.vue
Labels: UI/UX, application, feature

#49 Create separate components for assigned tasks.
  src/api/children.js
  src/components/BaseButton.vue
  src/components/BaseList.vue
  src/components/StripeCheckoutButton.vue
  src/components/TheHeader.vue
  src/components/tasks/AssignmentTaskList.vue
  src/components/tasks/AssignmentTaskListItem.vue
  src/components/tasks/TaskAssignModal.vue
  src/components/tasks/index.js
  src/compositions/useChildData.js
  src/compositions/useTasks.js
  src/routes.js
  src/store/children/actions.js
  src/store/children/mutations.js
  src/store/tasks/actions.js
  src/store/tasks/getters.js
  src/store/tasks/mutations.js
  src/store/user/mutations.js
  src/views/AuthPage.vue
  src/views/MainPage.vue
Labels: UI/UX, application, enhancement

#52 added delete button for assigned-tasks
  package-lock.json
  src/components/tasks/AssignmentTaskListItem.vue
Labels: application, feature
